/**
 * Electrobun build configuration.
 *
 * Active as of v0.2.1: `hutch electrobun dev --watch` runs src/bun/index.ts as
 * the main process and serves src/mainview into a native window. The Hutch
 * toolchain resolves the runtime and projects the SDK into .hutch/devkit —
 * run `hutch electrobun prepare` if that folder is missing.
 */

import type { ElectrobunConfig } from "electrobun";

export default {
  app: {
    name: "Nishi",
    identifier: "dev.nishi.editor",
    version: "0.2.1",
  },
  scripts: {
    // Compiles SCSS and rewrites the view's asset references. Must run before
    // the copy step below reads .build/.
    preBuild: "scripts/build-view.ts",
  },
  build: {
    // Electrobun's Bun-compatible main-process runtime.
    mainProcess: "cottontail",
    cottontail: {
      entrypoint: "src/bun/index.ts",
    },
    views: {
      mainview: {
        entrypoint: "src/mainview/index.ts",
      },
    },
    // Generated by scripts/build-view.ts (preBuild): the authored HTML with its
    // asset references rewritten, plus the compiled stylesheet.
    copy: {
      ".build/mainview/index.html": "views/mainview/index.html",
      ".build/mainview/index.css": "views/mainview/index.css",
      // Under views:// a leading-slash href resolves inside the view folder,
      // so these sit beside index.html rather than at the views root.
      "assets/icon.svg": "views/mainview/assets/icon.svg",
      "assets/icon.png": "views/mainview/assets/icon.png",
    },
    // System webview on every platform; no bundled Chromium.
    // Stage 6 revisits this when evaluating a Gecko renderer.
    mac: { bundleCEF: false },
    linux: { bundleCEF: false },
    win: { bundleCEF: false },
  },
} satisfies ElectrobunConfig;
