/**
 * Icon sprite builder.
 *
 * Inlines every icon Nishi uses into src/mainview/index.html as a hidden
 * <svg><symbol> block, referenced with <use href="#i-name">.
 *
 * Why inline rather than <img src="…">: under the desktop shell's views://
 * scheme an SVG comes back without a usable image MIME type and the webview
 * refuses to render it. Inline markup works identically in both hosts, needs no
 * runtime fetch, and inherits currentColor so icons theme themselves.
 *
 * Sources:
 *   - the Nishi mark, from the generated assets/icon.svg (see gen-icon.ts)
 *   - Lucide (ISC) icons, from the lucide-static package
 *
 * Run with `bun run sprite` after changing ICONS or regenerating the mark.
 */

import { readFileSync, writeFileSync } from "node:fs";

/** Lucide icon names to inline, by the role they play in the UI. */
const ICONS = [
  // Activity bar
  "folder-tree",
  "search",
  "blocks",
  "settings",

  // Explorer chrome
  "file-plus",
  "folder-plus",
  "refresh-cw",
  "ellipsis",
  "pencil",
  "trash-2",
  "chevron-right",
  "chevron-down",

  // Explorer entries
  "folder",
  "folder-open",
  "file",
  "file-code",
  "file-text",
  "file-json",
  "file-image",
  "file-cog",
  "file-lock",
  "book-open",
  "palette",
  "terminal",

  // Editor + find bar
  "x",
  "minus",
  "square",
  "arrow-up",
  "arrow-down",
  "replace",
  "replace-all",
  "columns-2",
  "case-sensitive",
  "whole-word",
  "regex",
  "panel-left-close",
] as const;

/** Strip the wrapper <svg> and keep the drawing commands. */
function innerOf(svg: string): string {
  return svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\s*<title>[\s\S]*?<\/title>/g, "")
    .trim();
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.trim() ? pad + line.trim() : ""))
    .filter(Boolean)
    .join("\n");
}

const symbols: string[] = [];

// --- Nishi mark -------------------------------------------------------------
// Filled artwork with its own gradients, so it does not take currentColor.
const mark = innerOf(readFileSync("assets/icon.svg", "utf8"));
symbols.push(
  `      <symbol id="nishi-mark" viewBox="0 0 100 100">\n${indent(mark, 8)}\n      </symbol>`,
);

// --- Lucide -----------------------------------------------------------------
// Stroke attributes live on the <symbol> so <use> inherits them; the stroke
// colour stays currentColor so icons follow the theme.
for (const name of ICONS) {
  let file: string;
  try {
    file = readFileSync(`node_modules/lucide-static/icons/${name}.svg`, "utf8");
  } catch {
    throw new Error(
      `build-sprite: lucide icon "${name}" not found. Check the name against node_modules/lucide-static/icons/.`,
    );
  }
  symbols.push(
    `      <symbol id="i-${name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" ` +
      `stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n` +
      `${indent(innerOf(file), 8)}\n      </symbol>`,
  );
}

const block = `    <!--
      Icon sprite — GENERATED, do not edit by hand. Run \`bun run sprite\`.

      Nishi mark: generated by scripts/gen-icon.ts.
      Other icons: Lucide (ISC) — https://lucide.dev — see THIRD_PARTY_LICENSE.md.

      Inlined rather than loaded: under the desktop shell's views:// scheme an
      SVG has no usable image MIME type and will not render in an <img>.
    -->
    <svg class="sprite" aria-hidden="true" focusable="false" width="0" height="0">
${symbols.join("\n")}
    </svg>
`;

let html = readFileSync("src/mainview/index.html", "utf8");

const existing = /^ {4}<!--\n {6}(Nishi mark|Icon sprite)[\s\S]*?<\/svg>\n/m;
html = existing.test(html)
  ? html.replace(existing, block)
  : html.replace(/(<body>\n)/, `$1${block}`);

writeFileSync("src/mainview/index.html", html);
console.log(`sprite: inlined nishi-mark + ${ICONS.length} Lucide icons`);
